from __future__ import annotations

INTENT_SLOT_CONTRACT = {
    "GREETING": {
        "required_slots": [],
        "optional_slots": ["language"],
        "clarify_prompt_tr": "",
        "validation_rules": [],
    },
    "SMALLTALK_CLOSING": {
        "required_slots": [],
        "optional_slots": [],
        "clarify_prompt_tr": "",
        "validation_rules": [],
    },
    "HOTEL_BOOKING_CREATE": {
        "required_slots": ["check_in_date", "check_out_date", "adult_count"],
        "optional_slots": [
            "child_count",
            "child_ages",
            "room_type",
            "board_type",
            "budget",
            "customer_name",
            "customer_phone",
            "customer_email",
            "special_requests",
        ],
        "clarify_prompt_tr": "Rezervasyon için giriş-çıkış tarihi ve kişi sayısını paylaşır mısınız?",
        "validation_rules": ["check_in_date>=today", "check_out_date>check_in_date", "adult_count>=1"],
    },
    "HOTEL_BOOKING_MODIFY": {
        "required_slots": ["booking_ref_or_match_key", "change_fields"],
        "optional_slots": [
            "new_check_in_date",
            "new_check_out_date",
            "new_adult_count",
            "new_child_count",
            "new_child_ages",
            "new_room_type",
            "new_special_requests",
        ],
        "clarify_prompt_tr": "Hangi rezervasyonu güncelleyelim? Rezervasyon kodu (CTX-...) veya telefon+isim paylaşır mısınız?",
        "validation_rules": ["booking_ref_or_match_key_required", "at_least_one_new_field_required"],
    },
    "HOTEL_BOOKING_CANCEL": {
        "required_slots": ["booking_ref_or_match_key"],
        "optional_slots": ["cancel_reason"],
        "clarify_prompt_tr": "İptal için rezervasyon kodunu (CTX-...) veya telefon+isim bilgisini paylaşır mısınız?",
        "validation_rules": ["booking_ref_or_match_key_required"],
    },
    "PRICE_QUERY": {
        "required_slots": ["check_in_date", "check_out_date", "adult_count"],
        "optional_slots": ["child_count", "child_ages", "room_type", "board_type", "currency", "budget"],
        "clarify_prompt_tr": "Net fiyat verebilmem için giriş-çıkış tarihi ve kişi sayısını paylaşır mısınız?",
        "validation_rules": ["check_in_date>=today", "check_out_date>check_in_date", "adult_count>=1"],
    },
    "AVAILABILITY_QUERY": {
        "required_slots": ["check_in_date", "check_out_date", "adult_count"],
        "optional_slots": ["child_count", "child_ages", "room_type"],
        "clarify_prompt_tr": "Müsaitlik için giriş-çıkış tarihi ve kişi sayısını paylaşır mısınız?",
        "validation_rules": ["check_in_date>=today", "check_out_date>check_in_date", "adult_count>=1"],
    },
    "RESTAURANT_BOOKING_CREATE": {
        "required_slots": ["reservation_date", "reservation_time", "guest_count", "reservation_name"],
        "optional_slots": ["phone", "seating_preference", "special_requests"],
        "clarify_prompt_tr": "Restoran rezervasyonu için tarih, saat, kişi sayısı ve isim paylaşır mısınız?",
        "validation_rules": ["reservation_date>=today", "guest_count>=1", "time_format_valid"],
    },
    "RESTAURANT_BOOKING_MODIFY": {
        "required_slots": ["restaurant_booking_ref_or_match_key", "change_fields"],
        "optional_slots": [
            "new_reservation_date",
            "new_reservation_time",
            "new_guest_count",
            "new_reservation_name",
            "new_seating_preference",
            "new_special_requests",
        ],
        "clarify_prompt_tr": "Hangi restoran rezervasyonunu güncelleyelim? Rezervasyon kodu veya telefon+isim paylaşır mısınız?",
        "validation_rules": ["ref_or_match_required", "at_least_one_new_field_required"],
    },
    "RESTAURANT_BOOKING_CANCEL": {
        "required_slots": ["restaurant_booking_ref_or_match_key"],
        "optional_slots": ["cancel_reason"],
        "clarify_prompt_tr": "İptal için restoran rezervasyon kodu veya telefon+isim paylaşır mısınız?",
        "validation_rules": ["ref_or_match_required"],
    },
    "TRANSFER_INFO": {
        "required_slots": [],
        "optional_slots": ["transfer_route", "transfer_type", "transfer_date", "transfer_time", "guest_count"],
        "clarify_prompt_tr": "",
        "validation_rules": [],
    },
    "TRANSFER_BOOKING_REQUEST": {
        "required_slots": ["transfer_date", "transfer_time", "flight_no", "guest_count", "route"],
        "optional_slots": ["luggage_count", "baby_seat", "customer_name", "customer_phone", "notes"],
        "clarify_prompt_tr": "Transfer talebi için tarih, saat, uçuş no, kişi sayısı ve rota paylaşır mısınız?",
        "validation_rules": ["transfer_date>=today", "guest_count>=1", "flight_no_format_basic"],
    },
    "PAYMENT_METHOD_QUERY": {
        "required_slots": [],
        "optional_slots": ["booking_ref", "currency"],
        "clarify_prompt_tr": "",
        "validation_rules": [],
    },
    "PAYMENT_LINK_REQUEST": {
        "required_slots": ["booking_ref"],
        "optional_slots": ["currency", "amount_preference"],
        "clarify_prompt_tr": "Ödeme linki için rezervasyon kodunu (CTX-...) paylaşır mısınız?",
        "validation_rules": ["booking_ref_required_for_all_users"],
    },
    "LOCAL_FAQ_INFO": {
        "required_slots": ["faq_topic"],
        "optional_slots": [],
        "clarify_prompt_tr": "Hangi konuda bilgi istiyorsunuz? (kahvaltı, WiFi, check-in/out, konum, sezon vb.)",
        "validation_rules": ["faq_topic_in_allowed_set"],
    },
    "COMPLAINT": {
        "required_slots": ["complaint_text"],
        "optional_slots": ["booking_ref", "severity_hint", "contact_preference"],
        "clarify_prompt_tr": "Yaşadığınız sorunu kısaca yazar mısınız? Varsa rezervasyon kodunu da ekleyin.",
        "validation_rules": ["complaint_text_min_length"],
    },
    "DISCOUNT_NEGOTIATION": {
        "required_slots": ["target_product_or_booking_context"],
        "optional_slots": ["budget", "date_range", "guest_count"],
        "clarify_prompt_tr": "Hangi rezervasyon/tarih için indirim talep ediyorsunuz?",
        "validation_rules": ["context_required"],
    },
    "HUMAN_AGENT_REQUEST": {
        "required_slots": [],
        "optional_slots": ["reason", "preferred_contact_time"],
        "clarify_prompt_tr": "",
        "validation_rules": [],
    },
    "SPECIAL_REQUEST_EVENT": {
        "required_slots": ["event_type"],
        "optional_slots": ["event_date", "booking_ref", "budget", "notes"],
        "clarify_prompt_tr": "Özel talebiniz için etkinlik türü ve tarihi paylaşır mısınız?",
        "validation_rules": ["event_type_in_allowed_set"],
    },
    "URGENT_CASE": {
        "required_slots": ["urgent_reason"],
        "optional_slots": ["booking_ref", "time_constraint", "contact_phone"],
        "clarify_prompt_tr": "Acil konuyu bir cümleyle ve varsa rezervasyon koduyla paylaşır mısınız?",
        "validation_rules": ["urgent_reason_required"],
    },
    "RISK_ABUSE": {
        "required_slots": ["risk_text"],
        "optional_slots": ["risk_type"],
        "clarify_prompt_tr": "",
        "validation_rules": ["auto_handoff_or_block"],
    },
    "AI_IDENTITY_QUESTION": {
        "required_slots": [],
        "optional_slots": [],
        "clarify_prompt_tr": "",
        "validation_rules": [],
    },
    "OUT_OF_SCOPE_OTHER": {
        "required_slots": [],
        "optional_slots": ["free_text_topic"],
        "clarify_prompt_tr": "Doğru yönlendirme için konunuzu tek cümleyle yazar mısınız?",
        "validation_rules": [],
    },
}

